export const OPERATION_MODULES = [
  {
    id: 'addition',
    title: 'Addition',
    bm: 'Tambah',
    symbol: '+',
    description: 'Combine quantities and find missing addends.',
    colour: 'blue',
    steps: [
      { prompt: 'What is 6 + 3?', expression: '6 + 3', options: ['9', '8', '10', '7'], answer: 0, explain: 'Six plus three makes nine.', hint: 'Start at 6 and count forward 3 steps.' },
      { prompt: 'What is 18 + 7?', expression: '18 + 7', options: ['25', '24', '26', '21'], answer: 0, explain: '18 + 7 = 25.', hint: 'Make 20 first: 18 + 2, then add the remaining 5.' },
      { prompt: 'Add 34 and 28.', expression: '34 + 28', options: ['62', '52', '68', '72'], answer: 0, explain: '34 + 28 = 62.', hint: 'Add tens and ones: 30 + 20, then 4 + 8.' },
      { prompt: 'What number completes the equation?', expression: '16 + ? = 25', options: ['9', '8', '11', '41'], answer: 0, explain: '16 needs 9 more to reach 25.', hint: 'Count from 16 up to 25.' },
      { prompt: 'A box has 27 red pencils and 15 blue pencils. How many altogether?', expression: '27 + 15', options: ['42', '32', '40', '52'], answer: 0, explain: '27 + 15 = 42 pencils.', hint: 'Altogether tells us to add.' },
    ],
  },
  {
    id: 'subtraction',
    title: 'Subtraction',
    bm: 'Tolak',
    symbol: '−',
    description: 'Find what remains and measure differences.',
    colour: 'teal',
    steps: [
      { prompt: 'What is 9 − 4?', expression: '9 − 4', options: ['5', '4', '6', '13'], answer: 0, explain: 'Nine take away four leaves five.', hint: 'Start at 9 and count back 4 steps.' },
      { prompt: 'What is 20 − 7?', expression: '20 − 7', options: ['13', '12', '14', '27'], answer: 0, explain: '20 − 7 = 13.', hint: 'Take away 10, then add 3 back.' },
      { prompt: 'Subtract 26 from 52.', expression: '52 − 26', options: ['26', '24', '36', '78'], answer: 0, explain: '52 − 26 = 26.', hint: 'Subtract 20 first, then subtract 6.' },
      { prompt: 'What number completes the equation?', expression: '? − 8 = 17', options: ['25', '9', '24', '26'], answer: 0, explain: '25 − 8 = 17.', hint: 'Reverse the operation: 17 + 8.' },
      { prompt: 'There were 63 stickers. 28 were used. How many remain?', expression: '63 − 28', options: ['35', '45', '31', '91'], answer: 0, explain: '63 − 28 = 35 stickers.', hint: 'Remain tells us to subtract.' },
    ],
  },
  {
    id: 'multiplication',
    title: 'Multiplication',
    bm: 'Darab',
    symbol: '×',
    description: 'Use equal groups, times tables, and missing factors.',
    colour: 'violet',
    steps: [
      { prompt: 'There are 3 groups of 4. How many objects altogether?', expression: '3 × 4', visual: { type: 'groups', groups: 3, perGroup: 4 }, options: ['12', '7', '9', '16'], answer: 0, explain: 'Three equal groups of four make twelve.', hint: 'Add 4 + 4 + 4.' },
      { prompt: 'What is 6 × 5?', expression: '6 × 5', options: ['30', '25', '35', '11'], answer: 0, explain: 'Six groups of five make thirty.', hint: 'Count by fives six times.' },
      { prompt: 'What is 7 × 8?', expression: '7 × 8', options: ['56', '54', '64', '15'], answer: 0, explain: '7 × 8 = 56.', hint: 'Use 7 × 4 = 28, then double it.' },
      { prompt: 'Which number completes the equation?', expression: '? × 4 = 36', options: ['9', '8', '10', '32'], answer: 0, explain: 'Nine groups of four make thirty-six.', hint: 'Think: 36 divided into groups of 4.' },
      { prompt: 'Six packs hold 8 pencils each. How many pencils are there?', expression: '6 × 8', options: ['48', '42', '14', '56'], answer: 0, explain: '6 × 8 = 48 pencils.', hint: 'Equal packs tell us to multiply.' },
    ],
  },
  {
    id: 'division',
    title: 'Division',
    bm: 'Bahagi',
    symbol: '÷',
    description: 'Share equally and connect division to multiplication.',
    colour: 'amber',
    steps: [
      { prompt: 'Share 12 objects equally among 3 groups. How many in each group?', expression: '12 ÷ 3', visual: { type: 'groups', groups: 3, perGroup: 4 }, options: ['4', '3', '6', '9'], answer: 0, explain: 'Twelve shared into three equal groups gives four each.', hint: 'What number multiplied by 3 makes 12?' },
      { prompt: 'What is 20 ÷ 5?', expression: '20 ÷ 5', options: ['4', '5', '10', '15'], answer: 0, explain: '20 divided by 5 equals 4.', hint: 'Use the fact 5 × 4 = 20.' },
      { prompt: 'What is 42 ÷ 6?', expression: '42 ÷ 6', options: ['7', '6', '8', '36'], answer: 0, explain: '42 divided by 6 equals 7.', hint: 'Use your six times table.' },
      { prompt: 'Which number completes the equation?', expression: '56 ÷ ? = 8', options: ['7', '6', '9', '48'], answer: 0, explain: '56 ÷ 7 = 8.', hint: 'Reverse it: 8 multiplied by what gives 56?' },
      { prompt: '36 pupils form teams of 9. How many teams are formed?', expression: '36 ÷ 9', options: ['4', '3', '5', '27'], answer: 0, explain: '36 divided into teams of 9 makes 4 teams.', hint: 'Teams of equal size tell us to divide.' },
    ],
  },
]

export const FRACTION_MODULES = [
  {
    id: 'fraction-foundations',
    title: 'Fraction foundations',
    bm: 'Asas pecahan',
    symbol: '½',
    description: 'Equal parts, numerator, denominator, and fractions of sets.',
    prerequisite: 'Division helps us split a whole into equal parts.',
    colour: 'blue',
    steps: [
      { prompt: 'One of two equal parts is shaded. Which fraction is shown?', visual: { type: 'fraction-bar', numerator: 1, denominator: 2 }, options: ['1/2', '1/3', '2/1', '2/2'], answer: 0, explain: 'One out of two equal parts is one-half.', hint: 'Count the shaded parts, then count all equal parts.' },
      { prompt: 'In 3/5, which number is the numerator?', expression: '3/5', options: ['3', '5', '8', '2'], answer: 0, explain: 'The numerator is the top number: 3.', hint: 'The numerator counts the selected parts.' },
      { prompt: 'In 3/5, which number is the denominator?', expression: '3/5', options: ['5', '3', '8', '2'], answer: 0, explain: 'The denominator is the bottom number: 5.', hint: 'The denominator tells how many equal parts make the whole.' },
      { prompt: 'Which fraction matches the shaded bar?', visual: { type: 'fraction-bar', numerator: 3, denominator: 4 }, options: ['3/4', '1/4', '4/3', '3/5'], answer: 0, explain: 'Three of four equal parts are shaded.', hint: 'There are 3 shaded parts out of 4 total parts.' },
      { prompt: 'What is one-third of 12?', expression: '1/3 of 12', options: ['4', '3', '6', '9'], answer: 0, explain: '12 divided into 3 equal groups gives 4 in each group.', hint: 'Divide 12 by the denominator, 3.' },
    ],
  },
  {
    id: 'equivalent-compare',
    title: 'Equivalent and compare',
    bm: 'Setara dan banding',
    symbol: '≡',
    description: 'Build equivalent fractions and compare their sizes.',
    prerequisite: 'Multiplication builds equivalent numerator-denominator pairs.',
    colour: 'teal',
    steps: [
      { prompt: 'Which fraction is equivalent to 1/2?', visual: { type: 'double-bar', fractions: [[1, 2], [2, 4]] }, options: ['2/4', '1/4', '2/3', '3/4'], answer: 0, explain: 'Multiplying the top and bottom by 2 gives 2/4.', hint: 'Two quarters cover the same amount as one half.' },
      { prompt: 'Complete the equivalent fraction.', expression: '2/3 = ?/6', options: ['4/6', '3/6', '2/6', '5/6'], answer: 0, explain: 'Multiply both 2 and 3 by 2 to get 4/6.', hint: 'The denominator doubled from 3 to 6. Double the numerator too.' },
      { prompt: 'Which fraction is larger?', expression: '3/5  or  2/5', options: ['3/5', '2/5', 'They are equal', 'Cannot tell'], answer: 0, explain: 'With equal denominators, compare the numerators.', hint: 'Both have fifths, so compare 3 parts with 2 parts.' },
      { prompt: 'Which fraction is larger?', expression: '3/4  or  3/8', options: ['3/4', '3/8', 'They are equal', 'Cannot tell'], answer: 0, explain: 'With equal numerators, fewer larger parts make the greater fraction.', hint: 'A fourth is larger than an eighth.' },
      { prompt: 'Which list is ordered from smallest to largest?', expression: '1/4, 2/4, 3/4', options: ['1/4, 2/4, 3/4', '3/4, 2/4, 1/4', '2/4, 1/4, 3/4', '1/4, 3/4, 2/4'], answer: 0, explain: 'With equal denominators, order the numerators.', hint: 'Compare 1, 2, and 3 equal-sized parts.' },
    ],
  },
  {
    id: 'fraction-add-subtract',
    title: 'Add and subtract fractions',
    bm: 'Tambah dan tolak pecahan',
    symbol: '±',
    description: 'Combine like parts and use common denominators.',
    prerequisite: 'Addition, subtraction, and multiplication are used here.',
    colour: 'violet',
    steps: [
      { prompt: 'Add fractions with the same denominator.', expression: '2/7 + 3/7', options: ['5/7', '5/14', '1/7', '6/7'], answer: 0, explain: 'Add the numerators and keep the denominator: 5/7.', hint: 'The parts are already the same size, so add 2 + 3.' },
      { prompt: 'Subtract fractions with the same denominator.', expression: '6/8 − 2/8', options: ['4/8', '4/0', '8/8', '3/8'], answer: 0, explain: 'Subtract the numerators and keep the denominator: 4/8.', hint: 'The eighths stay the same size. Subtract 6 − 2.' },
      { prompt: 'Find a common denominator, then add.', expression: '1/2 + 1/4', options: ['3/4', '2/6', '1/6', '2/4'], answer: 0, explain: 'Change 1/2 to 2/4, then 2/4 + 1/4 = 3/4.', hint: 'Rename one-half as two-quarters.' },
      { prompt: 'Find a common denominator, then subtract.', expression: '5/6 − 1/3', options: ['1/2', '4/3', '4/6', '2/3'], answer: 0, explain: 'Change 1/3 to 2/6. Then 5/6 − 2/6 = 3/6 = 1/2.', hint: 'Rename one-third using sixths.' },
      { prompt: 'A pupil reads 2/5 of a book on Monday and 1/5 on Tuesday. How much altogether?', expression: '2/5 + 1/5', options: ['3/5', '3/10', '1/5', '2/10'], answer: 0, explain: 'Two fifths plus one fifth equals three fifths.', hint: 'The denominator stays 5 because the parts are the same size.' },
    ],
  },
  {
    id: 'fraction-multiply-divide',
    title: 'Multiply and divide fractions',
    bm: 'Darab dan bahagi pecahan',
    symbol: '×÷',
    description: 'Find fractions of quantities and work with fraction operations.',
    prerequisite: 'Strong multiplication and division facts are important here.',
    colour: 'amber',
    steps: [
      { prompt: 'What is one-third of 12?', expression: '1/3 × 12', options: ['4', '3', '6', '9'], answer: 0, explain: 'Divide 12 by 3 to find one-third: 4.', hint: 'Share 12 into 3 equal groups.' },
      { prompt: 'Multiply a whole number by a fraction.', expression: '2 × 3/5', options: ['6/5', '5/6', '3/10', '6/10'], answer: 0, explain: 'Multiply 2 × 3 and keep the denominator: 6/5.', hint: 'Write 2 as 2/1, then multiply the numerators.' },
      { prompt: 'Multiply two fractions.', expression: '1/2 × 1/3', options: ['1/6', '2/3', '1/5', '2/6'], answer: 0, explain: 'Multiply tops and bottoms: 1 × 1 over 2 × 3 = 1/6.', hint: 'Multiply numerator by numerator and denominator by denominator.' },
      { prompt: 'Divide a fraction into 3 equal parts.', expression: '3/4 ÷ 3', options: ['1/4', '3/1', '9/4', '1/12'], answer: 0, explain: 'Three quarters shared into 3 equal groups gives one quarter each.', hint: 'Think: 3 quarter-pieces shared among 3 groups.' },
      { prompt: 'How many quarters fit inside one-half?', expression: '1/2 ÷ 1/4', options: ['2', '1', '3', '4'], answer: 0, explain: 'Two quarters make one-half, so the answer is 2.', hint: 'Rename one-half as two-quarters.' },
    ],
  },
]
